export const PROVIDE_NAME = {
  IMETRIC_DISTANCE: 'IMetricDistanceService',
  IMETRIC_TEMPERATURE: 'IMetricTemperatureService',
};

export enum METRIC_TYPE {
  DISTANCE = 'DISTANCE',
  TEMPERATURE = 'TEMPERATURE',
}

export enum METRIC_DISTANCE_UNIT {
  METER = 'meter',
  CENTIMETER = 'centimeter',
  INCH = 'inch',
  FEET = 'feet',
  YARD = 'yard',
}

export enum METRIC_TEMPERATURE_UNIT {
  C = 'C',
  F = 'F',
  K = 'K',
}


export const DISTANCE_CONVERSION_RATES = {
  [METRIC_DISTANCE_UNIT.METER]: {
    [METRIC_DISTANCE_UNIT.CENTIMETER]: 100,
    [METRIC_DISTANCE_UNIT.INCH]: 39.3701,
    [METRIC_DISTANCE_UNIT.FEET]: 3.28084,
    [METRIC_DISTANCE_UNIT.YARD]: 1.09361,
    [METRIC_DISTANCE_UNIT.METER]: 1,
  },
  [METRIC_DISTANCE_UNIT.CENTIMETER]: {
    [METRIC_DISTANCE_UNIT.METER]: 0.01,
    [METRIC_DISTANCE_UNIT.INCH]: 0.393701,
    [METRIC_DISTANCE_UNIT.FEET]: 0.0328084,
    [METRIC_DISTANCE_UNIT.YARD]: 0.0109361,
    [METRIC_DISTANCE_UNIT.CENTIMETER]: 1,
  },
  [METRIC_DISTANCE_UNIT.INCH]: {
    [METRIC_DISTANCE_UNIT.METER]: 0.0254,
    [METRIC_DISTANCE_UNIT.CENTIMETER]: 2.54,
    [METRIC_DISTANCE_UNIT.FEET]: 0.0833333,
    [METRIC_DISTANCE_UNIT.YARD]: 0.0277778,
    [METRIC_DISTANCE_UNIT.INCH]: 1,
  },
  [METRIC_DISTANCE_UNIT.FEET]: {
    [METRIC_DISTANCE_UNIT.METER]: 0.3048,
    [METRIC_DISTANCE_UNIT.CENTIMETER]: 30.48,
    [METRIC_DISTANCE_UNIT.INCH]: 12,
    [METRIC_DISTANCE_UNIT.YARD]: 0.333333,
    [METRIC_DISTANCE_UNIT.FEET]: 1,
  },
  [METRIC_DISTANCE_UNIT.YARD]: {
    [METRIC_DISTANCE_UNIT.METER]: 0.9144,
    [METRIC_DISTANCE_UNIT.CENTIMETER]: 91.44,
    [METRIC_DISTANCE_UNIT.INCH]: 36,
    [METRIC_DISTANCE_UNIT.FEET]: 3,
    [METRIC_DISTANCE_UNIT.YARD]: 1,
  },
};